### ISSUE TITLE
[proposal] Design update

### ISSUE THREAD

**Issue by zoepage** [tc39/tc39.github.io#12]
This is a proposal to update the current design including changes in the information architecture.

Above the fold, we'd have the 3 main topics that include the 4 main navigation points.
1. TC39 (about the project)
2. specs / contributie
3. state of proposal

The 3-grid copy is a "show-stopper" that would be supported though illustrations or icons and should give the user a first idea of the content of the site. The copy also gives various entry points though links to the internal content.

![tc39_black](https://user-images.githubusercontent.com/562354/38802977-1acaf8f6-416e-11e8-920b-471769e0c23f.png)

The navigation on the bottom of the page indicates the lower emphasis as the user should be focusing on the content above fold. While you scroll below the fold, the navigation bar would scroll up until it reached the top. It would stick to the top then and change the color to orange background and dark typo(#222). It would and also stay like this on every sub page.

I'll make more mocks for tablet and mobile view in the next few days.
Please note, this is a mockup and there are still small issues that will be fixed later on.

Thanks!

**Comment by iddan** [comment]
I like the content. I can argue about the UX

**Comment by codehag** [comment]
Thanks Ola, for the very well reasoned writeup of what is going on in this design, and thanks for going through the work of thinking this through! What I like about it is that it gives enough space for everything and makes a strong impression. It also keeps a lot of the information front and center for new users. Overall I like this direction very much.

Two concerns that I have at the moment:

1) the bottom menu: What i like about it is it works as a content divider, what I am not sure about is what happens if someone hovers one of these menu items, does the direction of the menu change?

2) "TC39" is repeated 4 times in the left column, I find this a bit distracting. I think there is a word for this but I forget at the moment how to express it. This partially has to do with the copy, but maybe we can find alternative way to do this... I have no ideas yet but I will think about it!

@iddan -- thanks for taking a look at this. Can you be a bit more specific when you say something like arguing about the UX? It would be good to be more constructive in our comments :)

**Comment by zoepage** [comment]
@codehag 
> I am not sure about is what happens if someone hovers one of these menu items, does the direction of the menu change?

What do you mean by `direction of the menu`? How the dropdown would open?

> TC39" is repeated 4 times in the left column, I find this a bit distracting. I think there is a word for this but I forget at the moment how to express it. This partially has to do with the copy, but maybe we can find alternative way to do this... I have no ideas yet but I will think about it!

 👍 on this. Maybe `project` or `about the project` would be already a direction we could go?

@iddan 

I second @codehag here. I'm interested in feedback, but it would be good to have something more constructive and specific, where a discussion is actually possible. Otherwise this might come off as passive-agressive. Thanks!

**Comment by iddan** [comment]
Sorry if that is the tone you read. I just wanted to set room for comments later. Really admire your work!

**Comment by iddan** [comment]
I think the logo should have some margin from the edge.

**Comment by Regaddi** [comment]
I think it might be helpful to visualize the transition of the navigation when switching from above to below the fold. If I understood correctly, the navigation bar will change colours and width. I am curious, when exactly this change is going to happen.

All in all it looks very clean to me and allows focus on the content 👍

**Comment by zoepage** [comment]
@Regaddi I was talking to @codehag today and we might get rid of the black navbar and the transition as we might end up with less content than we thought we would have. 

We also talked about an additional design for the wider screen. Will add mocks latest next week. :)

**Comment by codehag** [comment]
I just realized that the State of Proposals section isn't something we discussed. That should be named "contribute". the three segments don't need to map to one another.

**Comment by codehag** [comment]
@Regaddi have you already started?

**Comment by zoepage** [comment]
@codehag as we discussed, contribute is a section with content and links that provide information on how to contribute. The mockups just show variations of layout, not the end result. 

If you want to rename the proposal table, we can do that. Then we'd need to also rename the points in the navigation.

**Comment by Regaddi** [comment]
@codehag: Can you provide content for the above the fold boxes and the sections below? Are they even on the page at the same time?
