### ISSUE TITLE
Confusing link label for finished proposals in the website footer

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/tc39.github.io#217]
<img width="132" alt="image" src="https://user-images.githubusercontent.com/1507086/99200769-55b01180-27b8-11eb-9243-254d6664bcda.png">

The Stage 4 link points to finished proposals list and I wonder if it should be renamed accordingly. Stage 4 is (usually) a very short period of time when normative PR to the specification is opened, but not merged yet. Stage 4 name for such link could create some confusion about what stage 4 is. I'm not sure what is the best name here, but I think that "Finished proposals" or "Stage 4 and finished proposals" would be more correct and less confusing.

**Comment by DerekNonGeneric** [comment]
Hi @chicoxyzzy. Thanks for your concern. :)

Your understanding of stage 4 seems to align quite well with what is stated in the [process document](https://tc39.es/process-document/).

>   | Stage | Purpose
> -- | -- | --
> 0 | Strawperson | Allow input into the specification
> 1 | Proposal | <ul><li>Make the case for the addition</li><li>Describe the shape of a solution</li><li>Identify potential challenges</li>
> 2 | Draft | Precisely describe the syntax and semantics using formal spec language
> 3 | Candidate | Indicate that further refinement will require feedback from implementations and users
> 4 | Finished | Indicate that the addition is ready for inclusion in the formal ECMAScript standard
>
> &mdash; https://tc39.es/process-document/

&nbsp;

Since the process document equates “Stage 4” to “Finished” (and there appears to be room in this column of the footer for it), what might be able to do to avoid confusion and further clarify is to add the stage _name_ along with the stage _number_.

- Stage 0 - Strawperson
- Stage 1 - Proposal
- Stage 2 - Draft
- Stage 3 - Candidate
- Stage 4 - Finished

Do you think that would be an acceptable resolution for this issue?

**Comment by chicoxyzzy** [comment]
Finished proposals from https://github.com/tc39/proposals/blob/master/finished-proposals.md are mostly not on stage 4, but they are part of spec. Usually only few of them could be stage 4 for a very short period of time. We don't have a list of stage 4 proposals in the proposals repo, so I don't think that adding a name to stage 4 proposals link will solve the issue. I think that "stage 4" text should be either removed or the link title should be "Stage 4 and finished (or past?) proposals"

**Comment by chicoxyzzy** [comment]
There is no stage 4 proposals at the moment for example.

**Comment by ljharb** [comment]
There's no stage beyond 4, so in fact all of the finished proposals are stage 4. A stage 4 proposal is so whether it's merged into the spec already, or not.
