### ISSUE TITLE
tc39.es v2

### ISSUE THREAD

**Issue by smorimoto** [tc39/tc39.github.io#264]
As discussed in Matrix, we have a plan to rework the website. The current goals are still unclear and not too broad, but here are a few:

- Easy to contribute: The project is too chaotic. It must be able to bootstrap just with `npm i`.
- Responsive and accessible: As the title implies, there should be a better experience (particularly on mobile devices).
- Integrated with the dataset (optional): We already have the dataset and it would be nice if we could remove the need for manual updates based on it (except for translations), but we don't have any specific ideas on this yet, so it's completely optional.

**Comment by smorimoto** [comment]
At the moment, 11ty is a possible tool, but there may be a need for something more powerful. Especially when integrating with the dataset, we might want to use something more powerful.

**Comment by codehag** [comment]
I am not sure this is a plan, exactly yet, but please involve me if you do make plan to rework the website, I have been maintaining it. 

* Easy to contribute: the decision here was to use jekyll because it gave us an immediate way to deploy using github pages, without additional hosting or build steps. We have since grown out of that, but the only thing needed to boot strap is bundle install and jekyll serve.

* Responsive and accessible: I am happy to have contributions regarding accessibility and responsiveness. It would be better to identify specific issues. The work we did on the initial design was done intentionally. What do you have in mind?

* Integration with the dataset: This would be great, but the data set isn't complete yet. There is more work to do here. I am assuming you mean https://github.com/tc39/dataset

**Comment by smorimoto** [comment]
You're right. This is largely based on what I and @ryzokuken had in mind. Actually `bundle install` is not that annoying, but it's also known that it's not that friendly for (pure?) JavaScript developers.
Going further, the project is currently a bit weak on change, and sometimes it's like puzzling. See, for example, https://github.com/tc39/tc39.github.io/pull/249. The modern stuff isn't always better, but looking for better alternatives may not be a bad thing. For accessibility, the issue I found before seems to have been fixed somehow, so ignore it! It's my bad! I agree with you about the dataset. It's definitely what I was referring to, but as you say, it's still not that stable.
