### ISSUE TITLE
Do we need a HTML Linter?

### ISSUE THREAD

**Issue by jasonwilliams** [tc39/tc39.github.io#266]
Follow up from https://github.com/tc39/tc39.github.io/issues/265 

Is linting the HTML a requirement for this project? It's not something I've often seen employed in other projects similar to this.
It feels overkill but maybe there was a reason behind it.

Can the HTML changes be checked through code review? 
Are there tools that are generating the raw HTML anyway?

Related to: https://github.com/tc39/tc39.github.io/issues/264

**Comment by codehag** [comment]
My experience working with this is I had a failing build due to SVG having an unsupported field (an alt text field). But I haven't had many issues crop up. I would say that there hasn't been a significant benefit from the validation tools, including for css. That said, there are benefits to using these tools as they catch things that reviewers miss.

However, this is a small, light weight site which is intentionally using simple technologies. Due to the validation tools, I have had to do some modifications to the sass files that were not for the benefit of readability or correctness. I would say that re-evaluating the need for these tools is warranted.

**Comment by ryzokuken** [comment]
I agree that for the scale of this website, using heavyweight linting tools is really overkill.
