### ISSUE TITLE
Link/host ECMA-404

### ISSUE THREAD

**Issue by annevk** [tc39/tc39.github.io#283]
Would be nice to find it under specs (and maybe host it on tc39.es too).

**Comment by codehag** [comment]
Short term solution: We can host a copy of the pdf for now.

We need to get in touch with @FUDCo regarding the source, as I don't think we have an html equivalent to host.

**Comment by jasonwilliams** [comment]
I think those diagrams can be reproduced on [mermaid](https://mermaid-js.github.io/mermaid) but not entirely sure.

**Comment by annevk** [comment]
FWIW, @tabatkins wrote https://github.com/tabatkins/railroad-diagrams which seems fit for purpose. (Though conversion of the spec to HTML should probably be its own issue/project somewhere.)

**Comment by FUDCo** [comment]
The original source, derived from an earlier edition edited by Doug Crockford and Allen Wirfs-Brock, is a Microsoft Word file.  A copy should be in the ECMA archives somewhere, but if nobody can find it I'd be happy to pass along a copy to anybody who wants it.  Since the document is essentially frozen, we made a decision, many, many TC39 plenaries ago, that there was not a lot of payoff in rewriting it for the modern TC39 document workflow since it would be a fair amount of work with little to no benefit resulting.  But if there's some practical reason to convert it and somebody wants to sign up for the trouble, I'm happy to support that.

**Comment by ljharb** [comment]
@FUDCo i'd love to take a look at it.

**Comment by codehag** [comment]
>  But if there's some practical reason to convert it and somebody wants to sign up for the trouble, I'm happy to support that.

The main reason here would be to have it consistent with our other spec texts, hosted on the website and linked. We could host the PDF file, that is certainly possible. But, I think some folks have interest in rewriting it, and it would potentially be a good project for someone who wants to get some practice writing ecmarkup and get a deep read of 404. 

No real rush on this, in other words.

**Comment by FUDCo** [comment]
> I think some folks have interest in rewriting it, and it would potentially be a good project for someone who wants to get some practice writing ecmarkup and get a deep read of 404.

As I said, I'm happy to support such a project.  Though anyone undertaking it for ecmarkup practice should be aware that the experience might not generalize as well as they might hope since 404 is stylistically very different from the other specs.  It is, however, short, which might make it good practice after all.

**Comment by ctcpip** [comment]
`ECMA-414` is in the same boat, albeit just the sum of its parts

**Comment by ctcpip** [comment]
in the meantime, linking to the relevant Ecma pages (below) is preferable to their complete absence from the site

https://www.ecma-international.org/publications-and-standards/standards/ecma-404/
https://www.ecma-international.org/publications-and-standards/standards/ecma-414/
