### ISSUE TITLE
Increase information load and specificity of page heading

### ISSUE THREAD

**Issue by lukaszsobek** [tc39/tc39.github.io#78]
At the moment of writing the H1 page heading is "Specifying JavaScript". It feels like the amount of information the visitor obtains from this part of the web page could be increased to make the header more valuable to the reader. As such it would be great if the website presented to the visitor a complete information package about who does what. 

An idea would be to do the following:
![image](https://user-images.githubusercontent.com/23530054/42239409-1e5052f4-7f04-11e8-8d2a-2929c790425f.png)

- add a subheading explaining TC39 just by expanding the term
(now the the visitor knows who we are talking about and has the explanation of TC39)
- reshape the H1 message into a SVO (subject-verb-object) form in order to provide more information about who does what
(now the visitor knows that tc39 is a technical committee and it is responsible for shaping javascript).

ps. the word `shape` is just an example as it felt warmer in expression than the technical `specify`. Not sure about the fullstop/period at the end of the H1.

**Comment by ljharb** [comment]
TC39 doesn't just shape JS tho - it *defines* it.

**Comment by codehag** [comment]
Hi Lukasz, thanks for getting involved!

There was some thought put behind the headline before we decided on it. The thinking behind the heading "Specifying JavaScript" was to use an action that could also be applicable to the reader, yet was short enough to not need much concentration to absorb. If we state a subject, we imply too much. i.e. with "we", it is suggested that the committee is a "we" that is distinct from a "you" -- the reader. This would create a sense of a closed circle, one that doesn't include the reader. Since the purpose of this site is to open up the process to the public, this would be counter our goals.

With regards to giving more information: you will notice that we have three sub sections that are directly above the fold are meant to address the concern that you have about giving the user more immediate information. They cover the TC39, what the spec is, and how to contribute. 

If it feels better to people, we can change "specifying" to "defining", however the issue of the word will come up again, as we are working on a "specification". Happy to hear people's thoughts

**Comment by codehag** [comment]
Closing as we are currently happy with our communication
